name: Build
on: workflow_dispatch
jobs:

    build:
        name: Build
        runs-on: windows-latest
        steps:

            - name: Checkout
              uses: actions/checkout@v4

            - name: MSBuild
              uses: microsoft/setup-msbuild@v1.1

            - name: Build
              run: msbuild -property:Configuration=Release

            - name: Release
              uses: softprops/action-gh-release@v1
              with:
                files: Release/*.exe
                tag_name: 1.3.0
                fail_on_unmatched_files: true
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}